### ISSUE TITLE
Won't build for 1.26.0

### ISSUE THREAD

**Issue by nicbn** [starkat99/widestring-rs#13]
As of my PR #12, the library won't compile for Rust 1.26.0.
The options are to either stop supporting this version (which is pretty old already), which means we should bump the version as well as it is a breaking change, or to fix it.

I could try fixing it if 1.26.0 support is mandatory, but I don't see why it should be. I'd like some input on this.

**Comment by starkat99** [comment]
No, 1.26 support isn't necessary, it was just the previous minimum version. I'll update the CI version when I get a chance and do a new version release.
