### ISSUE TITLE
UCStr::from_ptr_with_nul & inconsistent documentation + behaviors around nulls

### ISSUE THREAD

**Issue by MaulingMonkey** [starkat99/widestring-rs#18]
The documentation here for `UCStr::from_ptr_with_nul` is a little self-contradictory - "Safety" claims the pointer mustn't be null, but then "Panics" documents safe behavior (panicing) on null, but then the implementation doesn't check for null and may or may hit debug-only asserts inside of `std`:

https://github.com/starkat99/widestring-rs/blob/e7236b62b9ffe8bf159644dfbf9b624060c8a843/src/ucstr.rs#L132

https://github.com/starkat99/widestring-rs/blob/e7236b62b9ffe8bf159644dfbf9b624060c8a843/src/ucstr.rs#L139

https://github.com/starkat99/widestring-rs/blob/e7236b62b9ffe8bf159644dfbf9b624060c8a843/src/ucstr.rs#L148-L152

Additionally, while `UCStr::from_ptr_with_nul` doesn't scan for nuls, it appears `UCString::from_ptr_with_nul` does (and will truncate) - and also handles the len=0 ptr=null case without panicing at all:

https://github.com/starkat99/widestring-rs/blob/e7236b62b9ffe8bf159644dfbf9b624060c8a843/src/ucstring.rs#L587-L597

calls:

https://github.com/starkat99/widestring-rs/blob/e7236b62b9ffe8bf159644dfbf9b624060c8a843/src/ucstring.rs#L181-L191

Should I create a PR for UCStr to try and return `&[UChar::NUL]` for the length 0 case?  (Maybe UCStr can gain a `Default` impl?) 
 Should it scan/truncate too (would change the result of `str.len()`)?  Perhaps matching function signatures?

The inconsistent "Safety" vs "Panics" documentation crops up in multiple places - should I try and drop this text from all the "Safety" sections where `p` is already null-checked soundly and documented to be null-checked under "Panics"?

> `p` must be non-null.

**Comment by starkat99** [comment]
Not surprised some inconsistencies have popped up, there was some significant internal refactoring. A PR to correct these would be welcome. 

> Should I create a PR for UCStr to try and return &[UChar::NUL] for the length 0 case? (Maybe UCStr can gain a Default impl?) Should it scan/truncate too (would change the result of str.len())? Perhaps matching function signatures?

In general, `_unchecked` methods should not scan/truncate, and methods that are passed a `len` parameter should scan and error on missing/unexpected nuls depending on signature. Methods that receive only the pointer should scan and truncate without error. This should be true for both UCStr and UCString. Getting the zero length behavior consistent would be useful
