### ISSUE TITLE
implement into_raw/from_raw for WideCString

### ISSUE THREAD

**Issue by chpio** [starkat99/widestring-rs#2]
[into_raw](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.into_raw)
[from_raw](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.from_raw)

**Comment by starkat99** [comment]
Added to 0.2.1

**Comment by chpio** [comment]
wow, thank you :)
