### ISSUE TITLE
Add `Display` implementation

### ISSUE THREAD

**Issue by joboet** [starkat99/widestring-rs#20]
It would be useful to be able to print strings directly without converting them to a String, thereby avoiding the allocation. 

While trying to implement this locally, I noticed that implementing `Display` automatically implies a `ToString` implementation, which conflicts with the current `to_string` functions as they return an error when encountering invalid code units, whereas my `Display` implementation performs the conversion lossily. Therefore, implementing `Display` would be a breaking change. 

Solutions I could think of:
* Rename the conversion methods
**Pro**: makes displaying strings convenient
**Con**: breaks the API and does not follow the naming guidelines
* Add a `display` method similar to `Path::display`
**Pro**: allows configuring different replacement options, like escaping invalid units
**Con**: is not as straightforward and complicates usage when using proc-macros like `thiserror`

**Comment by yuandrew** [comment]
I agree that having a `Display` impl would be very useful. 

I also think the default `Debug` impl should be swapped out for something more similar to the regular `String` debug implementation, instead of printing the underlying Vec as raw bytes.
