### ISSUE TITLE
Create an empty `U16CString`

### ISSUE THREAD

**Issue by ok-nick** [starkat99/widestring-rs#24]
It is possible to create an empty `U16String` using `U16String::new()`, although it is impossible to create an empty `U16CString`. It looks like the `::new()` method on a `U16CString` has been deprecated and so I could guess that you've been reluctant to introduce this function until you've removed the deprecated one (or never)? Is there any reason why we can't create an empty `U16CString` using some convenience method?

**Comment by starkat99** [comment]
The `Default` implementation is an empty string for all the string types. Old `new` to `from_vec` iirc to be more consistent. But there's no reason not to reintroduce it as an empty string in 1.0 as deprecated functions are removed, and it would also be more consistent with other types.
