### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by Binero** [starkat99/widestring-rs#5]
Just as a heads up, the link to the documentation on [crates.io](https://crates.io/crates/widestring) is broken.

**Comment by starkat99** [comment]
I'll be pushing 0.3 version of crate to crates.io soon, where the docs all link to docs.rs now. Thanks for the reminder that I need to do that soon.

**Comment by starkat99** [comment]
Crate.io apparently has a [bug](https://github.com/rust-lang/crates.io/issues/1214), the documentation link did not update when 0.3 was published. Crates.io at least shows the latest readme which has the correct links, just the main crates.io link is broken for now.

**Comment by starkat99** [comment]
This looks resolved now
