### ISSUE TITLE
WideCString.to_wide_string contains NULL value

### ISSUE THREAD

**Issue by snf** [starkat99/widestring-rs#7]
The documentation of [to_wide_string](https://docs.rs/widestring/0.3.0/widestring/struct.WideCString.html#method.to_wide_string) states that WideString won't contain the NULL value but it will because it's copying the underlying vector (which has a NULL value).

**Comment by starkat99** [comment]
This is working correctly, as the newly added doctest example demonstrates. `to_wide_string` calls `as_slice` before making the vector copy, which strips the NULL terminator.
